name: alittlecloud
description: A new Flutter project.
version: 1.0.0+1
environment:
    sdk: ">=2.16.1 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    splashscreen: ^1.3.5
    cupertino_icons: ^1.0.2
    firebase_core: ^1.13.1
    cloud_firestore: ^3.1.10
    flutter_svg: ^1.0.3
    google_fonts: ^2.3.1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
flutter:
    uses-material-design: true
    assets:
        - assets/images/
    fonts:
        - family: Icon3dot
          fonts:
              - asset: assets/icon/fonts/Icon3dot.ttf