/// Flutter icons Icon3dot
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon3dot
///      fonts:
///       - asset: fonts/Icon3dot.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Icon3dot {
  Icon3dot._();

  static const _kFontFam = 'Icon3dot';
  static const String? _kFontPkg = null;

  static const IconData dot_3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
